version: '3'

vars:
  BINARY_NAME: hyperv-runner-pool

silent: true

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build Windows binary
    env:
      CGO_ENABLED: "1"
    cmds:
      - GOOS=windows GOARCH=amd64 go build -ldflags "-H=windowsgui" -o {{.BINARY_NAME}}.exe ./cmd/hyperv-runner-pool

  build-local:
    desc: Build for current OS
    env:
      CGO_ENABLED: "1"
    cmds:
      - go build -ldflags "-H=windowsgui" -o {{.BINARY_NAME}} ./cmd/hyperv-runner-pool

  test:
    desc: Run unit tests (mock VM manager, orchestrator, concurrent operations)
    cmds:
      - go test -v ./...

  test-short:
    desc: Run quick tests only
    cmds:
      - go test -v -short ./...

  test-all:
    desc: Run all tests (same as test - no separate API tests)
    cmds:
      - task: test

  run:
    desc: Run orchestrator with mock VMs (serverless polling mode)
    env:
      USE_MOCK: "true"
    cmds:
      - go run ./cmd/hyperv-runner-pool -c config.yaml

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist/
      - rm -f {{.BINARY_NAME}} {{.BINARY_NAME}}.exe

  release-snapshot:
    desc: Build release snapshot (testing)
    cmds:
      - goreleaser build --snapshot --clean --single-target

  release-full:
    desc: Build all release artifacts (no publish)
    cmds:
      - goreleaser build --snapshot --clean

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  lint:
    desc: Run go vet
    cmds:
      - go vet ./...

  deps:
    desc: Download dependencies
    cmds:
      - go mod download
      - go mod tidy
